# Generated by Django 5.0 on 2025-11-03 14:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_constructor', models.BooleanField(default=False, help_text='Designates whether this user is a constructor (free user).', verbose_name='constructor status')),
                ('is_provider', models.BooleanField(default=False, help_text='Designates whether this user is a provider (subscription user).', verbose_name='provider status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Excavadora CAT 320"', max_length=255, verbose_name='machine name')),
                ('category', models.CharField(choices=[('excavator', 'Excavadora'), ('crane', 'Grúa'), ('truck', 'Camión'), ('transport', 'Transporte de Áridos'), ('loader', 'Cargador Frontal'), ('bulldozer', 'Bulldozer'), ('roller', 'Rodillo Compactador'), ('mixer', 'Mixer/Hormigonera'), ('pump', 'Bomba de Hormigón'), ('forklift', 'Grúa Horquilla'), ('other', 'Otro')], max_length=50, verbose_name='category')),
                ('description', models.TextField(blank=True, help_text='Detailed description, specifications, capacity, etc.', verbose_name='description')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='brand')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in local currency', max_digits=10, null=True, verbose_name='price per hour')),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate in local currency', max_digits=10, null=True, verbose_name='price per day')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck if machine is currently in use or under maintenance', verbose_name='currently available')),
                ('main_image', models.ImageField(help_text='Image is required for the machine', upload_to='machines/', verbose_name='main image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='constructor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(help_text='Name of the construction company', max_length=255, verbose_name='company name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region/state')),
                ('country', models.CharField(default='Chile', max_length=100, verbose_name='country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'constructor profile',
                'verbose_name_plural': 'constructor profiles',
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='provider_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(help_text='Name of the provider company', max_length=255, verbose_name='company name')),
                ('description', models.TextField(blank=True, help_text='Brief description of the company and services offered', verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='company logo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region/state')),
                ('country', models.CharField(default='Chile', max_length=100, verbose_name='country')),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled')], default='trial', max_length=20, verbose_name='subscription status')),
                ('subscription_start_date', models.DateField(blank=True, null=True, verbose_name='subscription start date')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='subscription end date')),
                ('available_within_48h', models.BooleanField(default=False, help_text='Toggle to indicate if you can provide services within 48 hours', verbose_name='available within 48 hours')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the provider has been verified by admin', verbose_name='verified')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from 0 to 5', max_digits=3, verbose_name='rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'provider profile',
                'verbose_name_plural': 'provider profiles',
                'ordering': ['-available_within_48h', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='participants')),
            ],
            options={
                'verbose_name': 'chat room',
                'verbose_name_plural': 'chat rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='machines/gallery/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.machine', verbose_name='machine')),
            ],
            options={
                'verbose_name': 'machine image',
                'verbose_name_plural': 'machine images',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False, help_text='Whether the message has been read by the recipient', verbose_name='read')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom', verbose_name='chat room')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='api.providerprofile', verbose_name='provider'),
        ),
    ]
