# Generated by Django 5.2.2 on 2025-11-13 13:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_load_categorias_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportista',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='transportista',
            name='base_geocodificada',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordenadas geocodificadas de la dirección empresarial (latitud, longitud)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='transportista',
            name='direccion_empresarial',
            field=models.CharField(blank=True, help_text='Dirección base de la empresa del transportista', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportista',
            name='radio_km',
            field=models.IntegerField(blank=True, help_text='Radio de actuación en kilómetros (solo si tipo_zona_actuacion == RADIO)', null=True),
        ),
        migrations.AddField(
            model_name='transportista',
            name='tipo_zona_actuacion',
            field=models.CharField(choices=[('RADIO', 'Radio'), ('ZONAS', 'Zonas')], default='RADIO', help_text='Tipo de zona de actuación: Radio (km) o Zonas (provincias/regiones)', max_length=10),
        ),
        migrations.AddField(
            model_name='transportista',
            name='zonas_definidas',
            field=models.JSONField(blank=True, help_text='Zonas definidas manualmente (solo si tipo_zona_actuacion == ZONAS). Ej: {"provincias": ["Madrid", "Barcelona"], "nacional": true}', null=True),
        ),
    ]
