# Generated by Django 5.2.2 on 2025-11-13 18:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_transportista_ubicacion_and_more'),
    ]

    operations = [
        # Paso 1: Eliminar campos antiguos
        migrations.RemoveField(
            model_name='transportista',
            name='direccion_empresarial',
        ),
        migrations.RemoveField(
            model_name='transportista',
            name='radio_km',
        ),
        # Paso 2: Añadir nuevos campos al modelo Transportista
        migrations.AddField(
            model_name='transportista',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal para geocodificar la base de actuación', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transportista',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del transportista (para el chat)', null=True, upload_to='transportistas/perfiles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='transportista',
            name='radio_km_general',
            field=models.IntegerField(blank=True, help_text='Radio de actuación general en kilómetros (usado si no hay radio_km_especifico en TransportistaCategoria)', null=True),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='base_geocodificada',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordenadas geocodificadas calculadas desde codigo_postal (latitud, longitud)', null=True, srid=4326),
        ),
        # Paso 3: Eliminar el campo M2M categorias (sin through) para poder recrearlo con through
        migrations.RemoveField(
            model_name='transportista',
            name='categorias',
        ),
        # Paso 4: Crear el modelo TransportistaCategoria (through)
        migrations.CreateModel(
            name='TransportistaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_km_especifico', models.IntegerField(blank=True, help_text='Radio de actuación específico para esta máquina en kilómetros. Si es null, usa radio_km_general del transportista', null=True)),
                ('imagen_maquina', models.ImageField(blank=True, help_text='Imagen de la máquina', null=True, upload_to='transportistas/maquinas/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría (máquina) del transportista', on_delete=django.db.models.deletion.CASCADE, related_name='transportistacategoria_set', to='db.categoria')),
                ('transportista', models.ForeignKey(help_text='Transportista propietario de esta máquina', on_delete=django.db.models.deletion.CASCADE, related_name='transportistacategoria_set', to='db.transportista')),
            ],
            options={
                'verbose_name': 'Máquina del Transportista',
                'verbose_name_plural': 'Máquinas de los Transportistas',
                'db_table': 'transportista_categoria',
            },
        ),
        # Paso 5: Recrear el campo M2M categorias con through
        migrations.AddField(
            model_name='transportista',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorías de transporte (maquinaria) que maneja este transportista', related_name='transportistas', through='db.TransportistaCategoria', to='db.categoria'),
        ),
        # Paso 6: Añadir índices y constraints
        migrations.AddIndex(
            model_name='transportistacategoria',
            index=models.Index(fields=['transportista', 'categoria'], name='transportis_transpo_296fd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transportistacategoria',
            unique_together={('transportista', 'categoria')},
        ),
    ]
