# Generated by Django 5.2.2 on 2025-11-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_remove_transportista_direccion_empresarial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportistacategoria',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Descripción detallada de características especiales del vehículo', null=True),
        ),
        migrations.AddField(
            model_name='transportistacategoria',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del vehículo (ej. "Mercedes", "Volvo", "Caterpillar")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportistacategoria',
            name='nombre_vehiculo',
            field=models.CharField(blank=True, help_text='Nombre personalizado del vehículo (ej. "Mi Furgoneta Mercedes")', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transportistacategoria',
            name='tonelaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tonelaje o capacidad de carga del vehículo', max_digits=10, null=True),
        ),
    ]
